// Generated by LiveScript 1.3.0
(function(){
  return ldc.register('nav', [], function(){
    return ldc.action({
      line: function(){
        return window.open("line://msg/text/" + encodeURIComponent(window.location.href), '_blank');
      },
      fb: function(){
        return window.open("http://www.facebook.com/sharer/sharer.php?u=" + window.location.href, '_blank');
      },
      twitter: function(){
        return window.open("http://twitter.com/share?url=" + window.location.href, '_blank');
      },
      ig: function(){
        return window.location.href = "https://www.instagram.com/pts.news/";
      }
    });
  });
})();